### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by AlexisBrasileiro** [Anuken/Mindustry-Suggestions#3409]
### Describe the content or mechanics you are proposing.

Recently, I acquired a ARM64 notebook (Galaxy Book Go)
Sadly, the x86 and 64bit emulation are a bit sluggish and draws a lot from my battery.

What are the odds for a new build with arm64 in mind for windows?

I just bought from Steam, and would love to see a ARM build there.

I have programming skills (mainly C# and Java, but I am a quick learner) I would like to help if possible/required - I can borrow my device for those builds.

Sadly, my birth language isn't english, so, my apologies for any grammar error or miscommunication.

Thanks in advance!

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be great for ARM devices, including Windows with ARM64

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have checked the [Trello](https://trello.com/b/aE2tcUwF/mindustry-trello) to make sure my suggestion isn't planned or implemented in a development version.
- [X] I am familiar with all the content already in the game or have glanced at the wiki to make sure my suggestion doesn't exist in the game yet.
- [X] I have read [README.md](https://github.com/Anuken/Mindustry-Suggestions/blob/master/README.md) to make sure my idea is not listed under the "A few things you shouldn't suggest" category.

**Comment by end-me-please** [comment]
it’s a Java game- why would that be a problem?

**Comment by Bottinator22** [comment]
Mindustry probably just doesn't come with ARM64 Java, if that even exists

**Comment by AlexisBrasileiro** [comment]
I use openJDK ARM64 for windows on my notebook
But Mindustry shows as x64 process and kills my battery
On my Linux Server (VM Debian x86 64bit) and my pi (zero W  - raspbian arm 32bits), I use oracle jdk with little to no problem

Sadly, I still can't dual boot on my notebook

**Comment by end-me-please** [comment]
You can just download the game from itch.io or GitHub to avoid that problem.

(The steam version is not some kind of premium version, it does not have more gameplay Features.)

**Comment by AlexisBrasileiro** [comment]
That was the very first thing I tried, but I only found 64 and 32 bits, both seems to be x86;

I know for a fact that  x86 32bit emulation are way more stable and reliable than x86 64bit (and draw less power)

But I would like to run as ARM64, because my notebook almost overheats everytime I try to run any game at x86 (both 32 and 64 bit)

I'm studying how to build as ARM64 using grapple on my spare time, if/when I get any progress, I can share with y'all

But if anyone can help me - or point me in the right direction - i would appreciate

**Comment by end-me-please** [comment]
Are you 100% sure that you are opening the .jar file with an ARM64 version of Java, and not some other version of Java that is installed somewhere?

**Comment by AlexisBrasileiro** [comment]
Running via Mindustry.exe, runs as x86 64bits
running via PowerShell i got 'Can't load AMD 64-bit .dll on a ARM 64-bit platform'

Here's the log:
PS C:\tmp\Mindustry\jre> java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Microsoft-25298 (build 16.0.2+7-ea)
OpenJDK 64-Bit Server VM Microsoft-25298 (build 16.0.2+7-ea, mixed mode)
PS C:\tmp\Mindustry\jre> java -jar .\desktop.jar
[E] arc.util.ArcRuntimeException: Couldn't load shared library 'arc64.dll' for target: Windows 10, 64-bit
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
        at arc.util.ArcNativesLoader.load(ArcNativesLoader.java:15)
        at arc.backend.sdl.SdlApplication.init(SdlApplication.java:71)
        at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:29)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: java.lang.UnsatisfiedLinkError: C:\Users\alexi\AppData\Local\Temp\arc\4862f228\arc64.dll: Can't load AMD 64-bit .dll on a ARM 64-bit platform
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:288)
        at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:81)
        ... 4 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\alexi\AppData\Local\Temp\arc\4862f228\arc64.dll: Can't load AMD 64-bit .dll on a ARM 64-bit platform
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
        at java.base/java.lang.Runtime.load0(Runtime.java:746)
        at java.base/java.lang.System.load(System.java:1857)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:294)
        at arc.util.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:260)
        ... 5 more

and here's the OpenJDK source:
https://github.com/microsoft/openjdk-aarch64/releases
(microsoft-jdk-16.0.2.7.1-windows-aarch64)

Microsoft's OpenJDK was my first shot, if you say I should try other version/distribution, I could try and get back to you

**Comment by hortiSquash** [comment]
its Arc thats concerned not Mindustry (the underlying engine)
https://github.com/Anuken/Arc

i'll add that support for ARM64 is already present but only for macOS, its just a problem with native libraries
![image](https://user-images.githubusercontent.com/45213805/156011793-db804cfe-6433-433c-adc9-9cf6a53647ce.png)
